const productsTypes = {
   SET_PRODUCTS: 'SET_PRODUCTS',
   SET_PRODUCTS_BY_CATEGORY: 'SET_PRODUCTS_BY_CATEGORY',
   SET_PRODUCT_BY_ID: 'SET_PRODUCT_BY_ID',
   CLEAR_PRODUCT_BY_ID: 'CLEAR_PRODUCT_BY_ID',
   SET_LOADED: 'SET_LOADED'
}

export default productsTypes