const authTypes = {
   SHOW_LOGIN_MESSAGE_SUCCESS: "SHOW_LOGIN_MESSAGE_SUCCESS",
   CURRENT_USER: "CURRENT_USER",
   IS_USER_ADMIN: "IS_USER_ADMIN",
   SET_USER_LOGOUT: "SET_USER_LOGOUT",
   SET_AUTH_ERROR: "SET_AUTH_ERROR",
   SET_USER_AUTH_LOADED: "SET_USER_AUTH_LOADED"
}

export default authTypes